<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.2.5" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.2.5" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.2.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Shared\BuildingBlocks.Messaging\BuildingBlocks.Messaging.csproj" />
		<ProjectReference Include="..\..\Core\Domain\Domain.csproj" />
		<ProjectReference Include="..\Persistence\Persistence.csproj" />
	</ItemGroup>

</Project>
